# Generated by Django 6.0.1 on 2026-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_user_alter_orderitem_quantity_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
