# Generated by Django 6.0.1 on 2026-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_coupon_code_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
