# Generated by Django 6.0.1 on 2026-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_gst_percent_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
