# Generated by Django 6.0.1 on 2026-02-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_created_at_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
